spring:
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/airbnb
    username: root
    password: park
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
        enabled: false
  jpa:
    #전송 쿼리 확인
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    #테이블 생성 후에 data.sql 실행
    defer-datasource-initialization : true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
logging:
  level:
    org.springframework.security: DEBUG
