spring:
  h2:
    console:
      enabled: false
#  devtools:
#    livereload:
#      enabled: true
#    remote:
#      restart:
#        enabled: true
#  datasource:
#    url: jdbc:mysql://localhost:3306/airbnb
#    username: root
#    password: park
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #전송 쿼리 확인
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #테이블 생성 후에 data.sql 실행
    defer-datasource-initialization : true
    hibernate:
      ddl-auto: validate
#  thymeleaf:
#    cache: false
#이슈 발급자, 비밀키를 필수로 성정해야 JWT 토큰을 만들 수 있습니다.
jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET_KEY}